# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\addresource\addresource.ui'
#
# Created: Wed May 28 15:23:43 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_addresource(object):
    def setupUi(self, addresource):
        addresource.setObjectName(_fromUtf8("addresource"))
        addresource.resize(412, 337)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(addresource.sizePolicy().hasHeightForWidth())
        addresource.setSizePolicy(sizePolicy)
        addresource.setMinimumSize(QtCore.QSize(412, 239))
        addresource.setMaximumSize(QtCore.QSize(412, 337))
        addresource.setSizeGripEnabled(False)
        self.SDP_IP = QtGui.QLineEdit(addresource)
        self.SDP_IP.setGeometry(QtCore.QRect(60, 28, 113, 20))
        self.SDP_IP.setObjectName(_fromUtf8("SDP_IP"))
        self.label = QtGui.QLabel(addresource)
        self.label.setGeometry(QtCore.QRect(20, 28, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.TEST = QtGui.QPushButton(addresource)
        self.TEST.setGeometry(QtCore.QRect(340, 27, 60, 23))
        self.TEST.setObjectName(_fromUtf8("TEST"))
        self.PORT = QtGui.QLineEdit(addresource)
        self.PORT.setGeometry(QtCore.QRect(210, 28, 51, 20))
        self.PORT.setObjectName(_fromUtf8("PORT"))
        self.label_2 = QtGui.QLabel(addresource)
        self.label_2.setGeometry(QtCore.QRect(180, 28, 46, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Result = QtGui.QTextBrowser(addresource)
        self.Result.setGeometry(QtCore.QRect(80, 194, 321, 101))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Result.sizePolicy().hasHeightForWidth())
        self.Result.setSizePolicy(sizePolicy)
        self.Result.setObjectName(_fromUtf8("Result"))
        self.label_3 = QtGui.QLabel(addresource)
        self.label_3.setGeometry(QtCore.QRect(20, 194, 30, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(addresource)
        self.line.setGeometry(QtCore.QRect(10, 50, 391, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_4 = QtGui.QLabel(addresource)
        self.label_4.setGeometry(QtCore.QRect(200, 69, 46, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.QAM_IP = QtGui.QLineEdit(addresource)
        self.QAM_IP.setEnabled(False)
        self.QAM_IP.setGeometry(QtCore.QRect(250, 70, 110, 20))
        self.QAM_IP.setObjectName(_fromUtf8("QAM_IP"))
        self.label_5 = QtGui.QLabel(addresource)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 71, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(addresource)
        self.label_6.setGeometry(QtCore.QRect(20, 134, 61, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.Frequency = QtGui.QLineEdit(addresource)
        self.Frequency.setGeometry(QtCore.QRect(81, 134, 91, 20))
        self.Frequency.setObjectName(_fromUtf8("Frequency"))
        self.label_7 = QtGui.QLabel(addresource)
        self.label_7.setGeometry(QtCore.QRect(176, 134, 70, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.FreqNumber = QtGui.QLineEdit(addresource)
        self.FreqNumber.setGeometry(QtCore.QRect(240, 134, 91, 20))
        self.FreqNumber.setObjectName(_fromUtf8("FreqNumber"))
        self.label_8 = QtGui.QLabel(addresource)
        self.label_8.setGeometry(QtCore.QRect(20, 96, 91, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.ServiceGroup = QtGui.QComboBox(addresource)
        self.ServiceGroup.setGeometry(QtCore.QRect(90, 94, 101, 21))
        self.ServiceGroup.setObjectName(_fromUtf8("ServiceGroup"))
        self.label_10 = QtGui.QLabel(addresource)
        self.label_10.setGeometry(QtCore.QRect(208, 100, 46, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.Status = QtGui.QComboBox(addresource)
        self.Status.setGeometry(QtCore.QRect(249, 94, 111, 21))
        self.Status.setObjectName(_fromUtf8("Status"))
        self.Status.addItem(_fromUtf8(""))
        self.Status.addItem(_fromUtf8(""))
        self.Status.addItem(_fromUtf8(""))
        self.Status.addItem(_fromUtf8(""))
        self.line_2 = QtGui.QFrame(addresource)
        self.line_2.setGeometry(QtCore.QRect(10, 114, 391, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_11 = QtGui.QLabel(addresource)
        self.label_11.setGeometry(QtCore.QRect(20, 164, 46, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.UdpPortsfrom = QtGui.QLineEdit(addresource)
        self.UdpPortsfrom.setGeometry(QtCore.QRect(80, 164, 37, 20))
        self.UdpPortsfrom.setObjectName(_fromUtf8("UdpPortsfrom"))
        self.label_12 = QtGui.QLabel(addresource)
        self.label_12.setGeometry(QtCore.QRect(122, 165, 13, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.UdpPortsto = QtGui.QLineEdit(addresource)
        self.UdpPortsto.setGeometry(QtCore.QRect(137, 164, 36, 20))
        self.UdpPortsto.setObjectName(_fromUtf8("UdpPortsto"))
        self.label_13 = QtGui.QLabel(addresource)
        self.label_13.setGeometry(QtCore.QRect(264, 168, 25, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.TSID = QtGui.QLineEdit(addresource)
        self.TSID.setGeometry(QtCore.QRect(290, 164, 41, 20))
        self.TSID.setObjectName(_fromUtf8("TSID"))
        self.Add = QtGui.QPushButton(addresource)
        self.Add.setGeometry(QtCore.QRect(340, 162, 61, 23))
        self.Add.setObjectName(_fromUtf8("Add"))
        self.QAM_NAME = QtGui.QComboBox(addresource)
        self.QAM_NAME.setGeometry(QtCore.QRect(90, 70, 101, 22))
        self.QAM_NAME.setObjectName(_fromUtf8("QAM_NAME"))
        self.Clear = QtGui.QPushButton(addresource)
        self.Clear.setGeometry(QtCore.QRect(340, 306, 61, 23))
        self.Clear.setObjectName(_fromUtf8("Clear"))
        self.Note = QtGui.QLabel(addresource)
        self.Note.setGeometry(QtCore.QRect(20, 6, 211, 16))
        self.Note.setObjectName(_fromUtf8("Note"))
        self.label_9 = QtGui.QLabel(addresource)
        self.label_9.setGeometry(QtCore.QRect(195, 167, 41, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.Interval = QtGui.QLineEdit(addresource)
        self.Interval.setGeometry(QtCore.QRect(240, 164, 18, 20))
        self.Interval.setObjectName(_fromUtf8("Interval"))

        self.retranslateUi(addresource)
        QtCore.QMetaObject.connectSlotsByName(addresource)
        addresource.setTabOrder(self.SDP_IP, self.PORT)
        addresource.setTabOrder(self.PORT, self.TEST)
        addresource.setTabOrder(self.TEST, self.QAM_NAME)
        addresource.setTabOrder(self.QAM_NAME, self.QAM_IP)
        addresource.setTabOrder(self.QAM_IP, self.ServiceGroup)
        addresource.setTabOrder(self.ServiceGroup, self.Status)
        addresource.setTabOrder(self.Status, self.Frequency)
        addresource.setTabOrder(self.Frequency, self.FreqNumber)
        addresource.setTabOrder(self.FreqNumber, self.UdpPortsfrom)
        addresource.setTabOrder(self.UdpPortsfrom, self.UdpPortsto)
        addresource.setTabOrder(self.UdpPortsto, self.Interval)
        addresource.setTabOrder(self.Interval, self.TSID)
        addresource.setTabOrder(self.TSID, self.Add)
        addresource.setTabOrder(self.Add, self.Result)
        addresource.setTabOrder(self.Result, self.Clear)

    def retranslateUi(self, addresource):
        addresource.setWindowTitle(_translate("addresource", "Addresource1.12", None))
        self.label.setText(_translate("addresource", "SDP_IP", None))
        self.TEST.setText(_translate("addresource", "Test", None))
        self.label_2.setText(_translate("addresource", "PORT", None))
        self.label_3.setText(_translate("addresource", "Result", None))
        self.label_4.setText(_translate("addresource", "QAM_IP", None))
        self.label_5.setText(_translate("addresource", "QAM_NAME", None))
        self.label_6.setText(_translate("addresource", "Frequency", None))
        self.label_7.setText(_translate("addresource", "FreqNumber", None))
        self.label_8.setText(_translate("addresource", "ServiceGroup", None))
        self.label_10.setText(_translate("addresource", "Status", None))
        self.Status.setItemText(0, _translate("addresource", "A", None))
        self.Status.setItemText(1, _translate("addresource", "R", None))
        self.Status.setItemText(2, _translate("addresource", "B", None))
        self.Status.setItemText(3, _translate("addresource", "P", None))
        self.label_11.setText(_translate("addresource", "UdpPorts", None))
        self.label_12.setText(_translate("addresource", "To", None))
        self.label_13.setText(_translate("addresource", "TSID", None))
        self.Add.setText(_translate("addresource", "Add", None))
        self.Clear.setText(_translate("addresource", "Clear", None))
        self.Note.setText(_translate("addresource", "Please check you SDP connetion firstly !!", None))
        self.label_9.setText(_translate("addresource", "Interval", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    addresource = QtGui.QDialog()
    ui = Ui_addresource()
    ui.setupUi(addresource)
    addresource.show()
    sys.exit(app.exec_())

