# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Code\addresource\addresourceforHamonic.ui'
#
# Created: Wed May 28 15:23:43 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_addresourceforHamonic(object):
    def setupUi(self, addresourceforHamonic):
        addresourceforHamonic.setObjectName(_fromUtf8("addresourceforHamonic"))
        addresourceforHamonic.setEnabled(True)
        addresourceforHamonic.resize(412, 337)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(addresourceforHamonic.sizePolicy().hasHeightForWidth())
        addresourceforHamonic.setSizePolicy(sizePolicy)
        addresourceforHamonic.setMinimumSize(QtCore.QSize(412, 239))
        addresourceforHamonic.setMaximumSize(QtCore.QSize(412, 337))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../grove.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        addresourceforHamonic.setWindowIcon(icon)
        addresourceforHamonic.setSizeGripEnabled(False)
        self.SDP_IP = QtGui.QLineEdit(addresourceforHamonic)
        self.SDP_IP.setGeometry(QtCore.QRect(82, 14, 89, 20))
        self.SDP_IP.setObjectName(_fromUtf8("SDP_IP"))
        self.label = QtGui.QLabel(addresourceforHamonic)
        self.label.setGeometry(QtCore.QRect(21, 14, 51, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.TEST = QtGui.QPushButton(addresourceforHamonic)
        self.TEST.setGeometry(QtCore.QRect(340, 13, 60, 23))
        self.TEST.setObjectName(_fromUtf8("TEST"))
        self.PORT = QtGui.QLineEdit(addresourceforHamonic)
        self.PORT.setGeometry(QtCore.QRect(250, 14, 51, 20))
        self.PORT.setObjectName(_fromUtf8("PORT"))
        self.label_2 = QtGui.QLabel(addresourceforHamonic)
        self.label_2.setGeometry(QtCore.QRect(211, 15, 30, 13))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Result = QtGui.QTextBrowser(addresourceforHamonic)
        self.Result.setGeometry(QtCore.QRect(80, 270, 251, 60))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Result.sizePolicy().hasHeightForWidth())
        self.Result.setSizePolicy(sizePolicy)
        self.Result.setObjectName(_fromUtf8("Result"))
        self.label_3 = QtGui.QLabel(addresourceforHamonic)
        self.label_3.setGeometry(QtCore.QRect(20, 273, 30, 13))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(addresourceforHamonic)
        self.line.setGeometry(QtCore.QRect(10, 36, 391, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_4 = QtGui.QLabel(addresourceforHamonic)
        self.label_4.setGeometry(QtCore.QRect(200, 55, 46, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.QAM_IP = QtGui.QLineEdit(addresourceforHamonic)
        self.QAM_IP.setEnabled(False)
        self.QAM_IP.setGeometry(QtCore.QRect(250, 56, 80, 22))
        self.QAM_IP.setObjectName(_fromUtf8("QAM_IP"))
        self.label_5 = QtGui.QLabel(addresourceforHamonic)
        self.label_5.setGeometry(QtCore.QRect(20, 56, 71, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(addresourceforHamonic)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 61, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.Frequency = QtGui.QLineEdit(addresourceforHamonic)
        self.Frequency.setGeometry(QtCore.QRect(81, 120, 91, 20))
        self.Frequency.setObjectName(_fromUtf8("Frequency"))
        self.label_7 = QtGui.QLabel(addresourceforHamonic)
        self.label_7.setGeometry(QtCore.QRect(204, 120, 40, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.FreqNumber = QtGui.QLineEdit(addresourceforHamonic)
        self.FreqNumber.setGeometry(QtCore.QRect(249, 120, 81, 20))
        self.FreqNumber.setObjectName(_fromUtf8("FreqNumber"))
        self.label_8 = QtGui.QLabel(addresourceforHamonic)
        self.label_8.setGeometry(QtCore.QRect(20, 82, 91, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.ServiceGroup = QtGui.QComboBox(addresourceforHamonic)
        self.ServiceGroup.setGeometry(QtCore.QRect(90, 80, 81, 21))
        self.ServiceGroup.setObjectName(_fromUtf8("ServiceGroup"))
        self.label_10 = QtGui.QLabel(addresourceforHamonic)
        self.label_10.setGeometry(QtCore.QRect(208, 86, 46, 13))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.Status = QtGui.QComboBox(addresourceforHamonic)
        self.Status.setGeometry(QtCore.QRect(249, 80, 81, 21))
        self.Status.setObjectName(_fromUtf8("Status"))
        self.Status.addItem(_fromUtf8(""))
        self.Status.addItem(_fromUtf8(""))
        self.Status.addItem(_fromUtf8(""))
        self.Status.addItem(_fromUtf8(""))
        self.line_2 = QtGui.QFrame(addresourceforHamonic)
        self.line_2.setGeometry(QtCore.QRect(10, 104, 391, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_11 = QtGui.QLabel(addresourceforHamonic)
        self.label_11.setGeometry(QtCore.QRect(20, 152, 46, 13))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.UdpPortsfrom = QtGui.QLineEdit(addresourceforHamonic)
        self.UdpPortsfrom.setGeometry(QtCore.QRect(80, 150, 36, 20))
        self.UdpPortsfrom.setObjectName(_fromUtf8("UdpPortsfrom"))
        self.label_12 = QtGui.QLabel(addresourceforHamonic)
        self.label_12.setGeometry(QtCore.QRect(122, 153, 13, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.UdpPortsto = QtGui.QLineEdit(addresourceforHamonic)
        self.UdpPortsto.setGeometry(QtCore.QRect(137, 150, 36, 20))
        self.UdpPortsto.setObjectName(_fromUtf8("UdpPortsto"))
        self.label_13 = QtGui.QLabel(addresourceforHamonic)
        self.label_13.setGeometry(QtCore.QRect(272, 153, 25, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.TSID = QtGui.QLineEdit(addresourceforHamonic)
        self.TSID.setGeometry(QtCore.QRect(297, 150, 33, 20))
        self.TSID.setObjectName(_fromUtf8("TSID"))
        self.Add = QtGui.QPushButton(addresourceforHamonic)
        self.Add.setEnabled(True)
        self.Add.setGeometry(QtCore.QRect(340, 148, 61, 23))
        self.Add.setObjectName(_fromUtf8("Add"))
        self.QAM_NAME = QtGui.QComboBox(addresourceforHamonic)
        self.QAM_NAME.setGeometry(QtCore.QRect(90, 56, 81, 22))
        self.QAM_NAME.setObjectName(_fromUtf8("QAM_NAME"))
        self.Clear = QtGui.QPushButton(addresourceforHamonic)
        self.Clear.setGeometry(QtCore.QRect(340, 308, 61, 23))
        self.Clear.setObjectName(_fromUtf8("Clear"))
        self.label_9 = QtGui.QLabel(addresourceforHamonic)
        self.label_9.setGeometry(QtCore.QRect(202, 153, 41, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.Interval = QtGui.QLineEdit(addresourceforHamonic)
        self.Interval.setGeometry(QtCore.QRect(250, 150, 20, 20))
        self.Interval.setObjectName(_fromUtf8("Interval"))
        self.line_3 = QtGui.QFrame(addresourceforHamonic)
        self.line_3.setGeometry(QtCore.QRect(10, 173, 391, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.isAppend = QtGui.QRadioButton(addresourceforHamonic)
        self.isAppend.setGeometry(QtCore.QRect(20, 189, 61, 16))
        self.isAppend.setObjectName(_fromUtf8("isAppend"))
        self.line_4 = QtGui.QFrame(addresourceforHamonic)
        self.line_4.setGeometry(QtCore.QRect(10, 213, 391, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.ServiceID_start = QtGui.QLineEdit(addresourceforHamonic)
        self.ServiceID_start.setEnabled(False)
        self.ServiceID_start.setGeometry(QtCore.QRect(250, 188, 80, 21))
        self.ServiceID_start.setObjectName(_fromUtf8("ServiceID_start"))
        self.label_14 = QtGui.QLabel(addresourceforHamonic)
        self.label_14.setGeometry(QtCore.QRect(152, 189, 91, 20))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.Append = QtGui.QPushButton(addresourceforHamonic)
        self.Append.setEnabled(False)
        self.Append.setGeometry(QtCore.QRect(340, 186, 60, 24))
        self.Append.setObjectName(_fromUtf8("Append"))
        self.isDelete = QtGui.QRadioButton(addresourceforHamonic)
        self.isDelete.setGeometry(QtCore.QRect(20, 230, 82, 17))
        self.isDelete.setObjectName(_fromUtf8("isDelete"))
        self.line_5 = QtGui.QFrame(addresourceforHamonic)
        self.line_5.setGeometry(QtCore.QRect(10, 250, 391, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.Delete = QtGui.QPushButton(addresourceforHamonic)
        self.Delete.setEnabled(False)
        self.Delete.setGeometry(QtCore.QRect(340, 230, 60, 23))
        self.Delete.setObjectName(_fromUtf8("Delete"))
        self.Reset = QtGui.QPushButton(addresourceforHamonic)
        self.Reset.setGeometry(QtCore.QRect(340, 272, 62, 25))
        self.Reset.setObjectName(_fromUtf8("Reset"))

        self.retranslateUi(addresourceforHamonic)
        QtCore.QObject.connect(self.isAppend, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Add.setDisabled)
        QtCore.QObject.connect(self.isAppend, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ServiceID_start.setEnabled)
        QtCore.QObject.connect(self.isAppend, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Append.setEnabled)
        QtCore.QObject.connect(self.isDelete, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Delete.setEnabled)
        QtCore.QObject.connect(self.isDelete, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.ServiceID_start.setDisabled)
        QtCore.QObject.connect(self.isDelete, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.FreqNumber.setDisabled)
        QtCore.QObject.connect(self.isDelete, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Interval.setDisabled)
        QtCore.QObject.connect(self.isDelete, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.TSID.setDisabled)
        QtCore.QObject.connect(self.isDelete, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Add.setDisabled)
        QtCore.QObject.connect(self.isDelete, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Frequency.setDisabled)
        QtCore.QObject.connect(self.isDelete, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.UdpPortsfrom.setDisabled)
        QtCore.QObject.connect(self.isDelete, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.UdpPortsto.setDisabled)
        QtCore.QObject.connect(self.isDelete, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.Status.setDisabled)
        QtCore.QObject.connect(self.Reset, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.Add.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(addresourceforHamonic)
        addresourceforHamonic.setTabOrder(self.SDP_IP, self.PORT)
        addresourceforHamonic.setTabOrder(self.PORT, self.TEST)
        addresourceforHamonic.setTabOrder(self.TEST, self.QAM_NAME)
        addresourceforHamonic.setTabOrder(self.QAM_NAME, self.QAM_IP)
        addresourceforHamonic.setTabOrder(self.QAM_IP, self.ServiceGroup)
        addresourceforHamonic.setTabOrder(self.ServiceGroup, self.Status)
        addresourceforHamonic.setTabOrder(self.Status, self.Frequency)
        addresourceforHamonic.setTabOrder(self.Frequency, self.FreqNumber)
        addresourceforHamonic.setTabOrder(self.FreqNumber, self.UdpPortsfrom)
        addresourceforHamonic.setTabOrder(self.UdpPortsfrom, self.UdpPortsto)
        addresourceforHamonic.setTabOrder(self.UdpPortsto, self.Interval)
        addresourceforHamonic.setTabOrder(self.Interval, self.TSID)
        addresourceforHamonic.setTabOrder(self.TSID, self.Add)
        addresourceforHamonic.setTabOrder(self.Add, self.isAppend)
        addresourceforHamonic.setTabOrder(self.isAppend, self.ServiceID_start)
        addresourceforHamonic.setTabOrder(self.ServiceID_start, self.Append)
        addresourceforHamonic.setTabOrder(self.Append, self.isDelete)
        addresourceforHamonic.setTabOrder(self.isDelete, self.Delete)
        addresourceforHamonic.setTabOrder(self.Delete, self.Result)
        addresourceforHamonic.setTabOrder(self.Result, self.Clear)

    def retranslateUi(self, addresourceforHamonic):
        addresourceforHamonic.setWindowTitle(_translate("addresourceforHamonic", "AddresourceforHamonic1.1", None))
        self.label.setText(_translate("addresourceforHamonic", "SDP_IP", None))
        self.TEST.setText(_translate("addresourceforHamonic", "Test", None))
        self.label_2.setText(_translate("addresourceforHamonic", "PORT", None))
        self.label_3.setText(_translate("addresourceforHamonic", "Result", None))
        self.label_4.setText(_translate("addresourceforHamonic", "QAM_IP", None))
        self.label_5.setText(_translate("addresourceforHamonic", "QAM_NAME", None))
        self.label_6.setText(_translate("addresourceforHamonic", "Frequency", None))
        self.label_7.setText(_translate("addresourceforHamonic", "FreqNo", None))
        self.label_8.setText(_translate("addresourceforHamonic", "ServiceGroup", None))
        self.label_10.setText(_translate("addresourceforHamonic", "Status", None))
        self.Status.setItemText(0, _translate("addresourceforHamonic", "A", None))
        self.Status.setItemText(1, _translate("addresourceforHamonic", "R", None))
        self.Status.setItemText(2, _translate("addresourceforHamonic", "B", None))
        self.Status.setItemText(3, _translate("addresourceforHamonic", "P", None))
        self.label_11.setText(_translate("addresourceforHamonic", "UdpPorts", None))
        self.label_12.setText(_translate("addresourceforHamonic", "To", None))
        self.label_13.setText(_translate("addresourceforHamonic", "TSID", None))
        self.Add.setText(_translate("addresourceforHamonic", "Add", None))
        self.Clear.setText(_translate("addresourceforHamonic", "Clear", None))
        self.label_9.setText(_translate("addresourceforHamonic", "Interval", None))
        self.Interval.setText(_translate("addresourceforHamonic", "1", None))
        self.isAppend.setText(_translate("addresourceforHamonic", "Append", None))
        self.label_14.setText(_translate("addresourceforHamonic", "Start of ServiceID", None))
        self.Append.setText(_translate("addresourceforHamonic", "Append", None))
        self.isDelete.setText(_translate("addresourceforHamonic", "Delete", None))
        self.Delete.setText(_translate("addresourceforHamonic", "Delete", None))
        self.Reset.setText(_translate("addresourceforHamonic", "Reset", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    addresourceforHamonic = QtGui.QDialog()
    ui = Ui_addresourceforHamonic()
    ui.setupUi(addresourceforHamonic)
    addresourceforHamonic.show()
    sys.exit(app.exec_())

